/**
 * PDF Generator Service
 * Creates PDF handouts, study guides, and reference cards from extracted content
 */

import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import type { ExtractedContent, Section, KeyTerm, QuizQuestion } from './content-extractor';

export type PDFType = 'handout' | 'study-guide' | 'reference-card' | 'quiz-only' | 'full';

export interface PDFOptions {
  type: PDFType;
  title: string;
  author?: string;
  includeAnswers?: boolean;
  pageSize?: 'a4' | 'letter';
  orientation?: 'portrait' | 'landscape';
  headerColor?: string;
  accentColor?: string;
}

const DEFAULT_OPTIONS: Partial<PDFOptions> = {
  pageSize: 'letter',
  orientation: 'portrait',
  headerColor: '#0891b2', // cyan-600
  accentColor: '#0e7490', // cyan-700
  includeAnswers: false,
};

// PDF styling constants
const MARGIN = 20;
const LINE_HEIGHT = 7;
const HEADER_HEIGHT = 25;

/**
 * Generate PDF from extracted content
 */
export async function generatePDF(
  content: ExtractedContent,
  options: PDFOptions
): Promise<Blob> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const pdf = new jsPDF({
    orientation: opts.orientation,
    unit: 'mm',
    format: opts.pageSize,
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN * 2;

  let yPosition = MARGIN;

  // Add header
  yPosition = addHeader(pdf, opts.title, opts.type, opts.headerColor!, pageWidth);

  // Add content based on type
  switch (opts.type) {
    case 'handout':
      yPosition = addHandoutContent(pdf, content, yPosition, contentWidth, pageHeight, opts);
      break;
    case 'study-guide':
      yPosition = addStudyGuideContent(pdf, content, yPosition, contentWidth, pageHeight, opts);
      break;
    case 'reference-card':
      yPosition = addReferenceCardContent(pdf, content, yPosition, contentWidth, pageHeight, opts);
      break;
    case 'quiz-only':
      yPosition = addQuizContent(pdf, content, yPosition, contentWidth, pageHeight, opts);
      break;
    case 'full':
      yPosition = addFullContent(pdf, content, yPosition, contentWidth, pageHeight, opts);
      break;
  }

  // Add footer with page numbers
  addFooter(pdf, opts.author);

  return pdf.output('blob');
}

/**
 * Add header to PDF
 */
function addHeader(
  pdf: jsPDF,
  title: string,
  type: PDFType,
  headerColor: string,
  pageWidth: number
): number {
  // Header background
  pdf.setFillColor(headerColor);
  pdf.rect(0, 0, pageWidth, HEADER_HEIGHT, 'F');

  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, MARGIN, 15);

  // Type badge
  const typeLabel = getTypeLabel(type);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(typeLabel, pageWidth - MARGIN - pdf.getTextWidth(typeLabel), 15);

  // Reset text color
  pdf.setTextColor(0, 0, 0);

  return HEADER_HEIGHT + 10;
}

/**
 * Get human-readable type label
 */
function getTypeLabel(type: PDFType): string {
  switch (type) {
    case 'handout':
      return 'Handout';
    case 'study-guide':
      return 'Study Guide';
    case 'reference-card':
      return 'Quick Reference';
    case 'quiz-only':
      return 'Assessment';
    case 'full':
      return 'Complete Materials';
    default:
      return '';
  }
}

/**
 * Add footer with page numbers
 */
function addFooter(pdf: jsPDF, author?: string): void {
  const pageCount = pdf.getNumberOfPages();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const pageWidth = pdf.internal.pageSize.getWidth();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);

    // Page number
    const pageText = `Page ${i} of ${pageCount}`;
    pdf.text(pageText, pageWidth / 2 - pdf.getTextWidth(pageText) / 2, pageHeight - 10);

    // Author/attribution
    if (author) {
      pdf.text(author, MARGIN, pageHeight - 10);
    }

    // Generated by
    const genText = 'Generated by VibePresenterPro';
    pdf.text(genText, pageWidth - MARGIN - pdf.getTextWidth(genText), pageHeight - 10);
  }
}

/**
 * Check and add new page if needed
 */
function checkPageBreak(
  pdf: jsPDF,
  yPosition: number,
  pageHeight: number,
  requiredSpace: number = 30
): number {
  if (yPosition + requiredSpace > pageHeight - 20) {
    pdf.addPage();
    return MARGIN + 10;
  }
  return yPosition;
}

/**
 * Add section heading
 */
function addSectionHeading(
  pdf: jsPDF,
  text: string,
  yPosition: number,
  accentColor: string,
  pageWidth: number
): number {
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(accentColor);
  pdf.text(text, MARGIN, yPosition);

  // Underline
  pdf.setDrawColor(accentColor);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, yPosition + 2, pageWidth - MARGIN, yPosition + 2);

  pdf.setTextColor(0, 0, 0);
  return yPosition + LINE_HEIGHT + 5;
}

/**
 * Add paragraph text with word wrap
 */
function addParagraph(
  pdf: jsPDF,
  text: string,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  fontSize: number = 10
): number {
  pdf.setFontSize(fontSize);
  pdf.setFont('helvetica', 'normal');

  const lines = pdf.splitTextToSize(text, contentWidth);

  for (const line of lines) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight);
    pdf.text(line, MARGIN, yPosition);
    yPosition += LINE_HEIGHT;
  }

  return yPosition;
}

/**
 * Add bullet point
 */
function addBulletPoint(
  pdf: jsPDF,
  text: string,
  yPosition: number,
  contentWidth: number,
  pageHeight: number
): number {
  yPosition = checkPageBreak(pdf, yPosition, pageHeight);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');

  // Bullet
  pdf.text('•', MARGIN, yPosition);

  // Text with indent
  const lines = pdf.splitTextToSize(text, contentWidth - 8);
  for (let i = 0; i < lines.length; i++) {
    if (i > 0) {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight);
    }
    pdf.text(lines[i], MARGIN + 8, yPosition);
    yPosition += LINE_HEIGHT;
  }

  return yPosition;
}

/**
 * Add handout content (summarized, key points focus)
 */
function addHandoutContent(
  pdf: jsPDF,
  content: ExtractedContent,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  opts: PDFOptions
): number {
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Learning Objectives
  if (content.objectives.length > 0) {
    yPosition = addSectionHeading(pdf, 'Learning Objectives', yPosition, opts.accentColor!, pageWidth);
    for (const obj of content.objectives) {
      yPosition = addBulletPoint(pdf, obj, yPosition, contentWidth, pageHeight);
    }
    yPosition += 5;
  }

  // Key Sections (summarized)
  for (const section of content.sections.filter(s => s.level <= 2)) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(section.heading, MARGIN, yPosition);
    yPosition += LINE_HEIGHT;

    // Add bullet points for section
    for (const point of section.bulletPoints.slice(0, 5)) {
      yPosition = addBulletPoint(pdf, point, yPosition, contentWidth, pageHeight);
    }
    yPosition += 3;
  }

  // Clinical Pearls
  if (content.clinicalPearls.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, '💡 Clinical Pearls', yPosition, opts.accentColor!, pageWidth);

    for (const pearl of content.clinicalPearls) {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight, 20);

      // Pearl box
      pdf.setFillColor(240, 249, 255); // Light cyan background
      pdf.roundedRect(MARGIN, yPosition - 5, contentWidth, 15, 2, 2, 'F');

      yPosition = addParagraph(pdf, pearl, yPosition, contentWidth - 4, pageHeight, 9);
      yPosition += 3;
    }
  }

  return yPosition;
}

/**
 * Add study guide content (comprehensive, with review questions)
 */
function addStudyGuideContent(
  pdf: jsPDF,
  content: ExtractedContent,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  opts: PDFOptions
): number {
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Table of Contents
  yPosition = addSectionHeading(pdf, 'Contents', yPosition, opts.accentColor!, pageWidth);
  for (const section of content.sections.filter(s => s.level <= 2)) {
    pdf.setFontSize(9);
    pdf.text(`• ${section.heading}`, MARGIN + 5, yPosition);
    yPosition += LINE_HEIGHT - 1;
  }
  yPosition += 10;

  // Learning Objectives
  if (content.objectives.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, 'Learning Objectives', yPosition, opts.accentColor!, pageWidth);
    content.objectives.forEach((obj, i) => {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight);
      pdf.setFontSize(10);
      pdf.text(`${i + 1}. ${obj}`, MARGIN, yPosition);
      yPosition += LINE_HEIGHT;
    });
    yPosition += 5;
  }

  // Full Sections
  for (const section of content.sections) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);

    const fontSize = section.level === 1 ? 12 : section.level === 2 ? 11 : 10;
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', 'bold');
    pdf.text(section.heading, MARGIN, yPosition);
    yPosition += LINE_HEIGHT;

    if (section.content) {
      yPosition = addParagraph(pdf, section.content, yPosition, contentWidth, pageHeight, 10);
    }

    for (const point of section.bulletPoints) {
      yPosition = addBulletPoint(pdf, point, yPosition, contentWidth, pageHeight);
    }
    yPosition += 5;
  }

  // Key Terms
  if (content.keyTerms.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, 'Key Terms', yPosition, opts.accentColor!, pageWidth);

    for (const { term, definition } of content.keyTerms) {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight, 15);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.text(term + ':', MARGIN, yPosition);
      pdf.setFont('helvetica', 'normal');
      const termWidth = pdf.getTextWidth(term + ': ');
      const defLines = pdf.splitTextToSize(definition, contentWidth - termWidth);
      pdf.text(defLines[0], MARGIN + termWidth, yPosition);
      yPosition += LINE_HEIGHT;
      for (let i = 1; i < defLines.length; i++) {
        pdf.text(defLines[i], MARGIN + 5, yPosition);
        yPosition += LINE_HEIGHT;
      }
    }
    yPosition += 5;
  }

  // Review Questions
  if (content.quizQuestions.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, 'Review Questions', yPosition, opts.accentColor!, pageWidth);

    content.quizQuestions.forEach((q, i) => {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight, 30);

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      yPosition = addParagraph(pdf, `${i + 1}. ${q.question}`, yPosition, contentWidth, pageHeight);

      pdf.setFont('helvetica', 'normal');
      q.options.forEach((opt, j) => {
        const letter = String.fromCharCode(65 + j);
        yPosition = addParagraph(pdf, `   ${letter}. ${opt}`, yPosition, contentWidth - 10, pageHeight, 9);
      });

      if (opts.includeAnswers && q.correctAnswer >= 0) {
        pdf.setFontSize(9);
        pdf.setTextColor(0, 128, 0);
        const ansLetter = String.fromCharCode(65 + q.correctAnswer);
        pdf.text(`Answer: ${ansLetter}`, MARGIN + 10, yPosition);
        yPosition += LINE_HEIGHT;
        if (q.explanation) {
          pdf.setTextColor(100, 100, 100);
          yPosition = addParagraph(pdf, q.explanation, yPosition, contentWidth - 10, pageHeight, 8);
        }
        pdf.setTextColor(0, 0, 0);
      }
      yPosition += 5;
    });
  }

  // Clinical Pearls
  if (content.clinicalPearls.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, '💡 High-Yield Points', yPosition, opts.accentColor!, pageWidth);

    for (const pearl of content.clinicalPearls) {
      yPosition = addBulletPoint(pdf, pearl, yPosition, contentWidth, pageHeight);
    }
  }

  return yPosition;
}

/**
 * Add reference card content (dense, pocket-sized)
 */
function addReferenceCardContent(
  pdf: jsPDF,
  content: ExtractedContent,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  opts: PDFOptions
): number {
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Use smaller font for reference card
  const smallFont = 8;

  // Two-column layout for reference card
  const colWidth = (contentWidth - 5) / 2;

  // Key Points (left column)
  let leftY = yPosition;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(opts.accentColor!);
  pdf.text('KEY POINTS', MARGIN, leftY);
  leftY += LINE_HEIGHT;
  pdf.setTextColor(0, 0, 0);

  for (const section of content.sections.filter(s => s.level <= 2).slice(0, 5)) {
    leftY = checkPageBreak(pdf, leftY, pageHeight);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'bold');
    pdf.text(section.heading, MARGIN, leftY);
    leftY += 5;

    pdf.setFont('helvetica', 'normal');
    for (const point of section.bulletPoints.slice(0, 3)) {
      const lines = pdf.splitTextToSize(`• ${point}`, colWidth);
      for (const line of lines) {
        leftY = checkPageBreak(pdf, leftY, pageHeight);
        pdf.text(line, MARGIN, leftY);
        leftY += 4;
      }
    }
    leftY += 2;
  }

  // Right column - Key Terms & Pearls
  let rightY = yPosition;
  const rightX = MARGIN + colWidth + 5;

  if (content.keyTerms.length > 0) {
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(opts.accentColor!);
    pdf.text('KEY TERMS', rightX, rightY);
    rightY += LINE_HEIGHT;
    pdf.setTextColor(0, 0, 0);

    for (const { term, definition } of content.keyTerms.slice(0, 8)) {
      rightY = checkPageBreak(pdf, rightY, pageHeight);
      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'bold');
      pdf.text(term, rightX, rightY);
      rightY += 4;
      pdf.setFont('helvetica', 'normal');
      const defLines = pdf.splitTextToSize(definition, colWidth);
      for (const line of defLines.slice(0, 2)) {
        pdf.text(line, rightX, rightY);
        rightY += 3.5;
      }
      rightY += 1;
    }
  }

  // Clinical Pearls at bottom
  yPosition = Math.max(leftY, rightY) + 10;

  if (content.clinicalPearls.length > 0) {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 30);

    pdf.setFillColor(255, 251, 235); // Warm yellow background
    pdf.roundedRect(MARGIN, yPosition - 3, contentWidth, content.clinicalPearls.length * 12 + 10, 2, 2, 'F');

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(opts.accentColor!);
    pdf.text('💡 REMEMBER', MARGIN + 3, yPosition + 3);
    yPosition += 8;
    pdf.setTextColor(0, 0, 0);

    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    for (const pearl of content.clinicalPearls.slice(0, 5)) {
      const lines = pdf.splitTextToSize(`• ${pearl}`, contentWidth - 6);
      for (const line of lines) {
        pdf.text(line, MARGIN + 3, yPosition);
        yPosition += 4;
      }
      yPosition += 2;
    }
  }

  return yPosition;
}

/**
 * Add quiz-only content
 */
function addQuizContent(
  pdf: jsPDF,
  content: ExtractedContent,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  opts: PDFOptions
): number {
  const pageWidth = pdf.internal.pageSize.getWidth();

  if (content.quizQuestions.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No quiz questions found in this content.', MARGIN, yPosition);
    return yPosition + 20;
  }

  // Instructions
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(100, 100, 100);
  pdf.text('Select the best answer for each question.', MARGIN, yPosition);
  yPosition += LINE_HEIGHT + 5;
  pdf.setTextColor(0, 0, 0);

  // Questions
  content.quizQuestions.forEach((q, i) => {
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);

    // Question
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    const qLines = pdf.splitTextToSize(`${i + 1}. ${q.question}`, contentWidth);
    for (const line of qLines) {
      pdf.text(line, MARGIN, yPosition);
      yPosition += LINE_HEIGHT;
    }

    // Options
    pdf.setFont('helvetica', 'normal');
    q.options.forEach((opt, j) => {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight);
      const letter = String.fromCharCode(65 + j);

      // Checkbox or letter
      pdf.setDrawColor(150, 150, 150);
      pdf.rect(MARGIN + 5, yPosition - 4, 4, 4);

      const optLines = pdf.splitTextToSize(`${letter}. ${opt}`, contentWidth - 15);
      for (let k = 0; k < optLines.length; k++) {
        pdf.text(optLines[k], MARGIN + 12, yPosition);
        yPosition += LINE_HEIGHT - 1;
      }
    });

    yPosition += 8;
  });

  // Answer Key (if requested)
  if (opts.includeAnswers) {
    pdf.addPage();
    yPosition = MARGIN + 10;

    yPosition = addSectionHeading(pdf, 'Answer Key', yPosition, opts.accentColor!, pageWidth);

    content.quizQuestions.forEach((q, i) => {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight, 25);

      const ansLetter = q.correctAnswer >= 0 ? String.fromCharCode(65 + q.correctAnswer) : '?';

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${i + 1}. ${ansLetter}`, MARGIN, yPosition);
      yPosition += LINE_HEIGHT;

      if (q.explanation) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(9);
        pdf.setTextColor(80, 80, 80);
        const expLines = pdf.splitTextToSize(q.explanation, contentWidth - 10);
        for (const line of expLines) {
          yPosition = checkPageBreak(pdf, yPosition, pageHeight);
          pdf.text(line, MARGIN + 5, yPosition);
          yPosition += LINE_HEIGHT - 1;
        }
        pdf.setTextColor(0, 0, 0);
      }
      yPosition += 3;
    });
  }

  return yPosition;
}

/**
 * Add full content (everything included)
 */
function addFullContent(
  pdf: jsPDF,
  content: ExtractedContent,
  yPosition: number,
  contentWidth: number,
  pageHeight: number,
  opts: PDFOptions
): number {
  // Combine all content types
  yPosition = addStudyGuideContent(pdf, content, yPosition, contentWidth, pageHeight, opts);

  // Add references at the end
  if (content.references.length > 0) {
    const pageWidth = pdf.internal.pageSize.getWidth();
    yPosition = checkPageBreak(pdf, yPosition, pageHeight, 40);
    yPosition = addSectionHeading(pdf, 'References', yPosition, opts.accentColor!, pageWidth);

    pdf.setFontSize(8);
    content.references.forEach((ref, i) => {
      yPosition = checkPageBreak(pdf, yPosition, pageHeight);
      const refLines = pdf.splitTextToSize(`${i + 1}. ${ref}`, contentWidth);
      for (const line of refLines) {
        pdf.text(line, MARGIN, yPosition);
        yPosition += 5;
      }
    });
  }

  return yPosition;
}

/**
 * Generate PDF from raw HTML (uses html2canvas)
 */
export async function generatePDFFromHTML(
  html: string,
  title: string,
  options?: Partial<PDFOptions>
): Promise<Blob> {
  // Create a hidden container for rendering
  const container = document.createElement('div');
  container.style.cssText = `
    position: absolute;
    left: -9999px;
    top: 0;
    width: 800px;
    background: white;
    padding: 40px;
  `;
  container.innerHTML = html;
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: options?.orientation || 'portrait',
      unit: 'mm',
      format: options?.pageSize || 'letter',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 10;

    // Add title
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title, 10, position);
    position += 10;

    // Add image (may span multiple pages)
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - position;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    return pdf.output('blob');
  } finally {
    document.body.removeChild(container);
  }
}

/**
 * Download PDF blob as file
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
